### ISSUE TITLE
add_wind_and_stack_open_area measure is broken as of E+ 9.6

### ISSUE THREAD

**Issue by shorowit** [BuildingPerformanceSimulation/openstudio-measures#24]
Reported at https://unmethours.com/question/76215/error-when-using-add-wind-and-stack-open-area-measure/

Since this measure is an EnergyPlus measure, it references surface properties by index. As of EnergyPlus v9.6, surfaces have a new Space property, so many of the referenced indices are off by 1. For example, [this](https://github.com/BuildingPerformanceSimulation/openstudio-measures/blob/021bf44db79d32d54c1c7f5ce144ba1d056078f3/lib/measures/add_wind_and_stack_open_area/measure.rb#L82]) needs to reference property 5, not 4. And all of the coordinates ([here](https://github.com/BuildingPerformanceSimulation/openstudio-measures/blob/021bf44db79d32d54c1c7f5ce144ba1d056078f3/lib/measures/add_wind_and_stack_open_area/measure.rb#L98-L112), [here](https://github.com/BuildingPerformanceSimulation/openstudio-measures/blob/021bf44db79d32d54c1c7f5ce144ba1d056078f3/lib/measures/add_wind_and_stack_open_area/measure.rb#L152-L160), etc.) need to be incremented by 1. Other changes may be needed, I haven't fully audited the measure.

**Comment by mdahlhausen** [comment]
Fixed with https://github.com/BuildingPerformanceSimulation/openstudio-measures/commit/c13b332bea890d61799032f3fec2c70e82b7e717
