### ISSUE TITLE
Add Wind and Stack Open Area is still Legacy version on the BCL

### ISSUE THREAD

**Issue by Ski90Moo** [BuildingPerformanceSimulation/openstudio-measures#25]
When will the updated version get put on the BCL?

**Comment by Ski90Moo** [comment]
Ok, I see this was converted from EP measure to an OS measure and it appears there is still a problem with the code...?

**Comment by mdahlhausen** [comment]
Both the OpenStudio measure version and the legacy EnergyPlus measure version are now available on BCL.
https://bcl.nrel.gov/results/?fq=bundle:measure&fq=measure_tags:Envelope.Fenestration&show_rows=25

**Comment by mdahlhausen** [comment]
@Ski90Moo Thanks for the tutorial video!  I added a link to it in the measure README.

**Comment by Ski90Moo** [comment]
@mdahlhausen Thanks!
